services:
  - type: web
    name: cloud-web    
    region: franckfurt
    plan: free
    runtime: node
    repo: https://github.com/shaina951/blueprint.git
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString

databases:
  - name: cloud-db
    region: franckfurt
    plan: free
    databaseName: cloud 
    user: cloud 