services:
  # nodejs web service
  - type: web
    name: cloud-web
    runtime: node
    region: franckfurt
    plan: free
    repo: https://github.com/shaina951/webservice.git # optional
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString

databases:
  - name: cloud-db
    region: franckfurt
    databaseName: cloud # optional (Render may add a suffix)
    user: cloud # optional
    plan: free
  

